/*
 * SC Controller - Uinput - Auto-generated arrays of keyboard buttons
 *
 * ========= THIS FILE IS AUTOGENERATED ==========
 * 
 * Generated by generate-keyboard-buttons.py from include/scc/input-event-codes.h
 * Probably don't edit by hand.
 */
#include "common.h"
#include <stdint.h>
#include <unistd.h>

static uint16_t _keyboard_buttons[] = {
	KEY_ESC,
	KEY_F1,
	KEY_F2,
	KEY_F3,
	KEY_F4,
	KEY_F5,
	KEY_F6,
	KEY_F7,
	KEY_F8,
	KEY_F9,
	KEY_F10,
	KEY_F11,
	KEY_F12,
	KEY_SYSRQ,
	KEY_SCROLLLOCK,
	KEY_PAUSE,
	KEY_GRAVE,
	KEY_1,
	KEY_2,
	KEY_3,
	KEY_4,
	KEY_5,
	KEY_6,
	KEY_7,
	KEY_8,
	KEY_9,
	KEY_0,
	KEY_MINUS,
	KEY_EQUAL,
	KEY_BACKSPACE,
	KEY_TAB,
	KEY_Q,
	KEY_W,
	KEY_E,
	KEY_R,
	KEY_T,
	KEY_Y,
	KEY_U,
	KEY_I,
	KEY_O,
	KEY_P,
	KEY_LEFTBRACE,
	KEY_RIGHTBRACE,
	KEY_ENTER,
	KEY_CAPSLOCK,
	KEY_A,
	KEY_S,
	KEY_D,
	KEY_F,
	KEY_G,
	KEY_H,
	KEY_J,
	KEY_K,
	KEY_L,
	KEY_SEMICOLON,
	KEY_APOSTROPHE,
	KEY_BACKSLASH,
	KEY_LEFTSHIFT,
	KEY_102ND,
	KEY_Z,
	KEY_X,
	KEY_C,
	KEY_V,
	KEY_B,
	KEY_N,
	KEY_M,
	KEY_COMMA,
	KEY_DOT,
	KEY_SLASH,
	KEY_RIGHTSHIFT,
	KEY_LEFTCTRL,
	KEY_LEFTMETA,
	KEY_LEFTALT,
	KEY_SPACE,
	KEY_RIGHTALT,
	KEY_RIGHTMETA,
	KEY_COMPOSE,
	KEY_RIGHTCTRL,
	KEY_INSERT,
	KEY_HOME,
	KEY_PAGEUP,
	KEY_DELETE,
	KEY_END,
	KEY_PAGEDOWN,
	KEY_UP,
	KEY_LEFT,
	KEY_DOWN,
	KEY_RIGHT,
	KEY_NUMLOCK,
	KEY_KPSLASH,
	KEY_KPASTERISK,
	KEY_KPMINUS,
	KEY_KP7,
	KEY_KP8,
	KEY_KP9,
	KEY_KPPLUS,
	KEY_KP4,
	KEY_KP5,
	KEY_KP6,
	KEY_KP1,
	KEY_KP2,
	KEY_KP3,
	KEY_KPENTER,
	KEY_KP0,
	KEY_KPDOT,
	KEY_CONFIG,
	KEY_PLAYPAUSE,
	KEY_MUTE,
	KEY_VOLUMEDOWN,
	KEY_VOLUMEUP,
	KEY_HOMEPAGE,
	KEY_PREVIOUSSONG,
	KEY_NEXTSONG,
	KEY_BACK,
	KEY_FORWARD,
};

static int32_t _keyboard_scancodes[] = {
	0x00000,	/* 0 - (not used) */
	0x70029,	/* 1 - KEY_ESC */
	0x7001e,	/* 2 - KEY_1 */
	0x7001f,	/* 3 - KEY_2 */
	0x70020,	/* 4 - KEY_3 */
	0x70021,	/* 5 - KEY_4 */
	0x70022,	/* 6 - KEY_5 */
	0x70023,	/* 7 - KEY_6 */
	0x70024,	/* 8 - KEY_7 */
	0x70025,	/* 9 - KEY_8 */
	0x70026,	/* 10 - KEY_9 */
	0x70027,	/* 11 - KEY_0 */
	0x7002d,	/* 12 - KEY_MINUS */
	0x7002e,	/* 13 - KEY_EQUAL */
	0x7002a,	/* 14 - KEY_BACKSPACE */
	0x7002b,	/* 15 - KEY_TAB */
	0x70014,	/* 16 - KEY_Q */
	0x7001a,	/* 17 - KEY_W */
	0x70008,	/* 18 - KEY_E */
	0x70015,	/* 19 - KEY_R */
	0x70017,	/* 20 - KEY_T */
	0x7001c,	/* 21 - KEY_Y */
	0x70018,	/* 22 - KEY_U */
	0x7000c,	/* 23 - KEY_I */
	0x70012,	/* 24 - KEY_O */
	0x70013,	/* 25 - KEY_P */
	0x7002f,	/* 26 - KEY_LEFTBRACE */
	0x70030,	/* 27 - KEY_RIGHTBRACE */
	0x70028,	/* 28 - KEY_ENTER */
	0x700e0,	/* 29 - KEY_LEFTCTRL */
	0x70004,	/* 30 - KEY_A */
	0x70016,	/* 31 - KEY_S */
	0x70007,	/* 32 - KEY_D */
	0x70009,	/* 33 - KEY_F */
	0x7000a,	/* 34 - KEY_G */
	0x7000b,	/* 35 - KEY_H */
	0x7000d,	/* 36 - KEY_J */
	0x7000e,	/* 37 - KEY_K */
	0x7000f,	/* 38 - KEY_L */
	0x70033,	/* 39 - KEY_SEMICOLON */
	0x70034,	/* 40 - KEY_APOSTROPHE */
	0x70035,	/* 41 - KEY_GRAVE */
	0x700e1,	/* 42 - KEY_LEFTSHIFT */
	0x70032,	/* 43 - KEY_BACKSLASH */
	0x7001d,	/* 44 - KEY_Z */
	0x7001b,	/* 45 - KEY_X */
	0x70006,	/* 46 - KEY_C */
	0x70019,	/* 47 - KEY_V */
	0x70005,	/* 48 - KEY_B */
	0x70011,	/* 49 - KEY_N */
	0x70010,	/* 50 - KEY_M */
	0x70036,	/* 51 - KEY_COMMA */
	0x70037,	/* 52 - KEY_DOT */
	0x70038,	/* 53 - KEY_SLASH */
	0x700e5,	/* 54 - KEY_RIGHTSHIFT */
	0x70055,	/* 55 - KEY_KPASTERISK */
	0x700e2,	/* 56 - KEY_LEFTALT */
	0x7002c,	/* 57 - KEY_SPACE */
	0x70039,	/* 58 - KEY_CAPSLOCK */
	0x7003a,	/* 59 - KEY_F1 */
	0x7003b,	/* 60 - KEY_F2 */
	0x7003c,	/* 61 - KEY_F3 */
	0x7003d,	/* 62 - KEY_F4 */
	0x7003e,	/* 63 - KEY_F5 */
	0x7003f,	/* 64 - KEY_F6 */
	0x70040,	/* 65 - KEY_F7 */
	0x70041,	/* 66 - KEY_F8 */
	0x70042,	/* 67 - KEY_F9 */
	0x70043,	/* 68 - KEY_F10 */
	0x70053,	/* 69 - KEY_NUMLOCK */
	0x70047,	/* 70 - KEY_SCROLLLOCK */
	0x7005f,	/* 71 - KEY_KP7 */
	0x70060,	/* 72 - KEY_KP8 */
	0x70061,	/* 73 - KEY_KP9 */
	0x70056,	/* 74 - KEY_KPMINUS */
	0x7005c,	/* 75 - KEY_KP4 */
	0x7005d,	/* 76 - KEY_KP5 */
	0x7005e,	/* 77 - KEY_KP6 */
	0x70057,	/* 78 - KEY_KPPLUS */
	0x70059,	/* 79 - KEY_KP1 */
	0x7005a,	/* 80 - KEY_KP2 */
	0x7005b,	/* 81 - KEY_KP3 */
	0x70062,	/* 82 - KEY_KP0 */
	0x70063,	/* 83 - KEY_KPDOT */
	0x00000,	/* 84 - (not used) */
	0x00000,	/* 85 - (not used) */
	0x70064,	/* 86 - KEY_102ND */
	0x70044,	/* 87 - KEY_F11 */
	0x70045,	/* 88 - KEY_F12 */
	0x00000,	/* 89 - (not used) */
	0x00000,	/* 90 - (not used) */
	0x00000,	/* 91 - (not used) */
	0x00000,	/* 92 - (not used) */
	0x00000,	/* 93 - (not used) */
	0x00000,	/* 94 - (not used) */
	0x00000,	/* 95 - (not used) */
	0x70058,	/* 96 - KEY_KPENTER */
	0x700e4,	/* 97 - KEY_RIGHTCTRL */
	0x70054,	/* 98 - KEY_KPSLASH */
	0x70046,	/* 99 - KEY_SYSRQ */
	0x700e6,	/* 100 - KEY_RIGHTALT */
	0x00000,	/* 101 - (not used) */
	0x7004a,	/* 102 - KEY_HOME */
	0x70052,	/* 103 - KEY_UP */
	0x7004b,	/* 104 - KEY_PAGEUP */
	0x70050,	/* 105 - KEY_LEFT */
	0x7004f,	/* 106 - KEY_RIGHT */
	0x7004d,	/* 107 - KEY_END */
	0x70051,	/* 108 - KEY_DOWN */
	0x7004e,	/* 109 - KEY_PAGEDOWN */
	0x70049,	/* 110 - KEY_INSERT */
	0x7004c,	/* 111 - KEY_DELETE */
	0x00000,	/* 112 - (not used) */
	0xc00e2,	/* 113 - KEY_MUTE */
	0xc00ea,	/* 114 - KEY_VOLUMEDOWN */
	0xc00e9,	/* 115 - KEY_VOLUMEUP */
	0x00000,	/* 116 - (not used) */
	0x00000,	/* 117 - (not used) */
	0x00000,	/* 118 - (not used) */
	0x70048,	/* 119 - KEY_PAUSE */
	0x00000,	/* 120 - (not used) */
	0x00000,	/* 121 - (not used) */
	0x00000,	/* 122 - (not used) */
	0x00000,	/* 123 - (not used) */
	0x00000,	/* 124 - (not used) */
	0x700e3,	/* 125 - KEY_LEFTMETA */
	0x700e7,	/* 126 - KEY_RIGHTMETA */
	0x70065,	/* 127 - KEY_COMPOSE */
	0x00000,	/* 128 - (not used) */
	0x00000,	/* 129 - (not used) */
	0x00000,	/* 130 - (not used) */
	0x00000,	/* 131 - (not used) */
	0x00000,	/* 132 - (not used) */
	0x00000,	/* 133 - (not used) */
	0x00000,	/* 134 - (not used) */
	0x00000,	/* 135 - (not used) */
	0x00000,	/* 136 - (not used) */
	0x00000,	/* 137 - (not used) */
	0x00000,	/* 138 - (not used) */
	0x00000,	/* 139 - (not used) */
	0x00000,	/* 140 - (not used) */
	0x00000,	/* 141 - (not used) */
	0x00000,	/* 142 - (not used) */
	0x00000,	/* 143 - (not used) */
	0x00000,	/* 144 - (not used) */
	0x00000,	/* 145 - (not used) */
	0x00000,	/* 146 - (not used) */
	0x00000,	/* 147 - (not used) */
	0x00000,	/* 148 - (not used) */
	0x00000,	/* 149 - (not used) */
	0x00000,	/* 150 - (not used) */
	0x00000,	/* 151 - (not used) */
	0x00000,	/* 152 - (not used) */
	0x00000,	/* 153 - (not used) */
	0x00000,	/* 154 - (not used) */
	0x00000,	/* 155 - (not used) */
	0x00000,	/* 156 - (not used) */
	0x00000,	/* 157 - (not used) */
	0xc00f2,	/* 158 - KEY_BACK */
	0xc00f3,	/* 159 - KEY_FORWARD */
	0x00000,	/* 160 - (not used) */
	0x00000,	/* 161 - (not used) */
	0x00000,	/* 162 - (not used) */
	0xc00f1,	/* 163 - KEY_NEXTSONG */
	0xc00cd,	/* 164 - KEY_PLAYPAUSE */
	0xc00f0,	/* 165 - KEY_PREVIOUSSONG */
	0x00000,	/* 166 - (not used) */
	0x00000,	/* 167 - (not used) */
	0x00000,	/* 168 - (not used) */
	0x00000,	/* 169 - (not used) */
	0x00000,	/* 170 - (not used) */
	0xc0183,	/* 171 - KEY_CONFIG */
};

uint16_t* keyboard_buttons = &_keyboard_buttons[0];
int32_t* keyboard_scancodes = &_keyboard_scancodes[0];

size_t keyboard_button_count = sizeof(_keyboard_buttons) / sizeof(uint16_t);
size_t keyboard_scancode_count = sizeof(_keyboard_scancodes) / sizeof(int32_t);

