/*
 * SC Controller - Virtual devices on X11 - Auto-generated arrays of keyboard buttons
 *
 * ========= THIS FILE IS AUTOGENERATED ==========
 * 
 * Generated by generate-keyboard-buttons.py from include/scc/input-event-codes.h
 * Probably don't edit by hand.
 */
#include "scc/input-event-codes.h"
#include <stdint.h>
#include <unistd.h>

static uint32_t _keyboard_x11_keycodes[] = {
	0x00000,	/* 0 - (not used) */
	0x00009,	/* 1 - KEY_ESC */
	0x0000a,	/* 2 - KEY_1 */
	0x0000b,	/* 3 - KEY_2 */
	0x0000c,	/* 4 - KEY_3 */
	0x0000d,	/* 5 - KEY_4 */
	0x0000e,	/* 6 - KEY_5 */
	0x0000f,	/* 7 - KEY_6 */
	0x00010,	/* 8 - KEY_7 */
	0x00011,	/* 9 - KEY_8 */
	0x00012,	/* 10 - KEY_9 */
	0x00013,	/* 11 - KEY_0 */
	0x00014,	/* 12 - KEY_MINUS */
	0x00015,	/* 13 - KEY_EQUAL */
	0x00016,	/* 14 - KEY_BACKSPACE */
	0x00017,	/* 15 - KEY_TAB */
	0x00018,	/* 16 - KEY_Q */
	0x00019,	/* 17 - KEY_W */
	0x0001a,	/* 18 - KEY_E */
	0x0001b,	/* 19 - KEY_R */
	0x0001c,	/* 20 - KEY_T */
	0x0001d,	/* 21 - KEY_Y */
	0x0001e,	/* 22 - KEY_U */
	0x0001f,	/* 23 - KEY_I */
	0x00020,	/* 24 - KEY_O */
	0x00021,	/* 25 - KEY_P */
	0x00022,	/* 26 - KEY_LEFTBRACE */
	0x00023,	/* 27 - KEY_RIGHTBRACE */
	0x00024,	/* 28 - KEY_ENTER */
	0x00025,	/* 29 - KEY_LEFTCTRL */
	0x00026,	/* 30 - KEY_A */
	0x00027,	/* 31 - KEY_S */
	0x00028,	/* 32 - KEY_D */
	0x00029,	/* 33 - KEY_F */
	0x0002a,	/* 34 - KEY_G */
	0x0002b,	/* 35 - KEY_H */
	0x0002c,	/* 36 - KEY_J */
	0x0002d,	/* 37 - KEY_K */
	0x0002e,	/* 38 - KEY_L */
	0x0002f,	/* 39 - KEY_SEMICOLON */
	0x00030,	/* 40 - KEY_APOSTROPHE */
	0x00000,	/* 41 - (not used) */
	0x00032,	/* 42 - KEY_LEFTSHIFT */
	0x00033,	/* 43 - KEY_BACKSLASH */
	0x00034,	/* 44 - KEY_Z */
	0x00035,	/* 45 - KEY_X */
	0x00036,	/* 46 - KEY_C */
	0x00037,	/* 47 - KEY_V */
	0x00038,	/* 48 - KEY_B */
	0x00039,	/* 49 - KEY_N */
	0x0003a,	/* 50 - KEY_M */
	0x0003b,	/* 51 - KEY_COMMA */
	0x0003c,	/* 52 - KEY_DOT */
	0x0003d,	/* 53 - KEY_SLASH */
	0x0003e,	/* 54 - KEY_RIGHTSHIFT */
	0x0003f,	/* 55 - KEY_KPASTERISK */
	0x00040,	/* 56 - KEY_LEFTALT */
	0x00041,	/* 57 - KEY_SPACE */
	0x00042,	/* 58 - KEY_CAPSLOCK */
	0x00043,	/* 59 - KEY_F1 */
	0x00044,	/* 60 - KEY_F2 */
	0x00045,	/* 61 - KEY_F3 */
	0x00046,	/* 62 - KEY_F4 */
	0x00047,	/* 63 - KEY_F5 */
	0x00048,	/* 64 - KEY_F6 */
	0x00049,	/* 65 - KEY_F7 */
	0x0004a,	/* 66 - KEY_F8 */
	0x0004b,	/* 67 - KEY_F9 */
	0x0004c,	/* 68 - KEY_F10 */
	0x0004d,	/* 69 - KEY_NUMLOCK */
	0x0004e,	/* 70 - KEY_SCROLLLOCK */
	0x00000,	/* 71 - (not used) */
	0x00000,	/* 72 - (not used) */
	0x00000,	/* 73 - (not used) */
	0x00052,	/* 74 - KEY_KPMINUS */
	0x00000,	/* 75 - (not used) */
	0x00000,	/* 76 - (not used) */
	0x00000,	/* 77 - (not used) */
	0x00056,	/* 78 - KEY_KPPLUS */
	0x00000,	/* 79 - (not used) */
	0x00000,	/* 80 - (not used) */
	0x00000,	/* 81 - (not used) */
	0x00000,	/* 82 - (not used) */
	0x00000,	/* 83 - (not used) */
	0x00000,	/* 84 - (not used) */
	0x00000,	/* 85 - (not used) */
	0x0003d,	/* 86 - KEY_102ND */
	0x0005f,	/* 87 - KEY_F11 */
	0x00060,	/* 88 - KEY_F12 */
	0x00000,	/* 89 - (not used) */
	0x00000,	/* 90 - (not used) */
	0x00000,	/* 91 - (not used) */
	0x00000,	/* 92 - (not used) */
	0x00000,	/* 93 - (not used) */
	0x00000,	/* 94 - (not used) */
	0x00000,	/* 95 - (not used) */
	0x00068,	/* 96 - KEY_KPENTER */
	0x00069,	/* 97 - KEY_RIGHTCTRL */
	0x0006a,	/* 98 - KEY_KPSLASH */
	0x0006b,	/* 99 - KEY_SYSRQ */
	0x0006c,	/* 100 - KEY_RIGHTALT */
	0x00000,	/* 101 - (not used) */
	0x00000,	/* 102 - (not used) */
	0x0006f,	/* 103 - KEY_UP */
	0x00070,	/* 104 - KEY_PAGEUP */
	0x00071,	/* 105 - KEY_LEFT */
	0x00072,	/* 106 - KEY_RIGHT */
	0x00073,	/* 107 - KEY_END */
	0x00074,	/* 108 - KEY_DOWN */
	0x00075,	/* 109 - KEY_PAGEDOWN */
	0x00076,	/* 110 - KEY_INSERT */
	0x00077,	/* 111 - KEY_DELETE */
	0x00000,	/* 112 - (not used) */
	0x00000,	/* 113 - (not used) */
	0x00000,	/* 114 - (not used) */
	0x00000,	/* 115 - (not used) */
	0x00000,	/* 116 - (not used) */
	0x00000,	/* 117 - (not used) */
	0x00000,	/* 118 - (not used) */
	0x0007f,	/* 119 - KEY_PAUSE */
	0x00000,	/* 120 - (not used) */
	0x00000,	/* 121 - (not used) */
	0x00000,	/* 122 - (not used) */
	0x00000,	/* 123 - (not used) */
	0x00000,	/* 124 - (not used) */
	0x00071,	/* 125 - KEY_LEFTMETA */
	0x00071,	/* 126 - KEY_RIGHTMETA */
};

uint32_t* keyboard_x11_keycodes = &_keyboard_x11_keycodes[0];
size_t keyboard_x11_keycode_count = sizeof(_keyboard_x11_keycodes) / sizeof(uint32_t);

