#!/usr/bin/python2
from scc.sccdaemon import SCCDaemon
from scc.paths import get_pid_file, get_daemon_socket
from scc.tools import init_logging

import os, argparse

def main():
	init_logging()
	parser = argparse.ArgumentParser()
	parser.add_argument('profile', type=str)
	parser.add_argument('command', type=str, choices=['start', 'stop', 'restart', 'debug'])
	parser.add_argument('--alone', action='store_true', help="prevent scc-daemon from launching osd-daemon and autoswitch-daemon.")
	daemon = SCCDaemon(get_pid_file(), get_daemon_socket())
	args = parser.parse_args()
	daemon.alone = args.alone
	daemon.set_default_profile(args.profile)

	if 'start' == args.command:
		daemon.start()
	elif 'stop' == args.command:
		daemon.stop()
	elif 'restart' == args.command:
		daemon.restart()
	elif 'debug' == args.command:
		daemon.debug()


if __name__ == '__main__':
	main()
